# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2834ba8ff7c98e877370a70b8ebacc9942d6a4aac6d5efb9f610d1a95d67709d416176c2c578489a7318adac98549298c9fe24fb4e47c3f37deccb0f651e1e73

test:
  secret_key_base: 90cfc4a44171557ffcbc85b7d027140167ca49e78b6518ed9ba2a80756e3a0b269cbd97e4b524f9aa9a59f955d1bafc6bbe498e9cad5041cad3088b95f68be87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
